version: '3.8'
services:
  redis:
    container_name: redis-drawers-wars
    image: redis:latest
    ports:
      - '1111:1111'
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf