version: '3.8'
services:
  redis-drawers-wars:
    container_name: redis-drawers-wars
    image: redis:latest
    ports:
      - '1111:1111'
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - redis-drawers-wars:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
  backend-drawers-wars:
    container_name: backend-drawers-wars
    build: .
    ports:
      - '3001:3001'
    depends_on:
      - redis-drawers-wars
    environment:
      - REDIS_URL=redis://redis-drawers-wars:1111
volumes:
  redis-drawers-wars: